# Copyright (C) 2011 Jacob Beard
# Released under GNU LGPL, read the file 'COPYING' for more information

define ->
	[
		"actionSend/send1.json"
		"actionSend/send2.json"
		"actionSend/send3.json"
		"actionSend/send4.json"
		"actionSend/send5.json"
		"actionSend/send6.json"
		"actionSend/send7.json"
		"actionSend/send8.json"
		"assign/test0.json"
		"assign/test1.json"
		"assign/test2.json"
		"assign/test3.json"
		"basic/basic0.json"
		"basic/basic1.json"
		"basic/basic2.json"
		"cond-js/test0.json"
		"cond-js/test1.json"
		"cond-js/test2.json"
		"cond-js/TestConditionalTransition.json"
		"delayedSend/send1.json"
		"delayedSend/send2.json"
		"delayedSend/send3.json"
		"documentOrder/documentOrder0.json"
		"hierarchy+documentOrder/test0.json"
		"hierarchy+documentOrder/test1.json"
		"hierarchy/hier0.json"
		"hierarchy/hier1.json"
		"hierarchy/hier2.json"
		"history/history0.json"
		"history/history1.json"
		"history/history2.json"
		"history/history3.json"
		"history/history4.json"
		"history/history5.json"
	]

