image: node

pages:
  stage: deploy
  before_script:
  - npm
  script:
  - cd drag-and-drop-redux
  - npm install
  - mkdir ../public
  - cp -r * public/
  artifacts:
    paths:
    - public
  only:
  - master
