before_script:
   - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
   - npm install

.build_template: &build_definition
  script:
   - (cd projects/libraries/core && echo Running tests for core && npm ci && npm run test)
   - (cd projects/libraries/scxml && echo Running tests for scxml && npm ci && npm run test)

build:node:18:
  image: node:18
  <<: *build_definition

build:node:20:
  image: node:20
  <<: *build_definition

build:node:22:
  image: node:22
  <<: *build_definition
